### PR TITLE
WIP: Properties

### PR DESCRIPTION
**Pull request by sezna**
Things that I hope to get done in this PR:
* More tests for multi dimension rendering
* Tests for properties
* rendering clefs, dynamics, authors, and time signatures
* indexing of lists

### CODE REVIEW

**Comment by sezna** [comment]
Still needs:
* More property tests
* More metadata than just author
* Bar lines

**Comment by sezna** [comment]
Turns out abc2ly and ABC support in general is not there. Merging this in, and then abandoning the ABC music renderer in favor of directly generating Lilypond.

**Comment by Ameobea** [comment]
> Turns out abc2ly and ABC support in general is not there
Damn, that's too bad.  Will generating Lilypond will be a significantly bigger challenge than you were hoping for with ABC?

**Comment by sezna** [comment]
It shouldn't be too bad -- it is just a more complicated syntax. abc2ly doesn't support dynamics, so I filed a bug via GNU mailing list and got this response:

> 
> I don't think abc2ly is very actively supported and developed currently.
> 
> The future is in improving musicxml in/export for LilyPond.
> 
> There is xml2abc and xml2abc by Wim Vree, these are quite good:
> 
> https://wim.vree.org/svgParse/xml2abc.html
> https://wim.vree.org/svgParse/abc2xml.html
> 
> 
> And there is musicxml2ly to convert musicxml to lilypond.
> This probably works better now already than abc2ly.
> 
> And MusicXML can be imported in all major Music typesetting programs like
> Finale, Sibelius, Dorico, and MuseScore. 

I might also do musicXML out. Rendering engines can be swapped out so it isn't all one or the other. Those ABC to  musicXML scripts were generating xml that lilypond wasn't recognizing, though.

FWIW, abc2ly is just [this giant python script](https://github.com/lilypond/lilypond/blob/master/scripts/abc2ly.py) that hasn't been touched in a while.

**Pull request merged**
